---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-dest
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: scribe.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: restore
spec:
  trigger:
    manual: restore-once
  restic:
    repository: restic-repo
    destinationPVC: data-dest
    copyMethod: None
    cacheCapacity: 1Gi
